# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Julia Lanier
title: Graduate Research Assistant 
University of Michigan
email: jlanier@umich.edu
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: juliakaylanier
github_username:  JuliaKay23
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: julialanier
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/MI.jpg
about_content: | # this will include new lines to allow paragraphs
  
  I am a computer science and engineering PhD student at the University of Michigan. I am working with [Dr. Kevin Fu](https://web.eecs.umich.edu/~kevinfu/){:target="_blank"} with a research focus in security and privacy.
  
  My current [resume](/Resume.pdf){:target="_blank"}.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in computer science and engineering some of my other interests and hobbies are:
   - Hiking
   - Traveling
   - Coffee
   - Pokémon Go

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
